# Generated by Django 5.2.3 on 2025-08-04 11:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="平台名称"),
                ),
                (
                    "platform_type",
                    models.CharField(
                        choices=[("web", "Web Platform"), ("api", "API Platform")],
                        max_length=10,
                        verbose_name="平台类型",
                    ),
                ),
                ("base_url", models.URLField(blank=True, verbose_name="基础URL")),
                ("config", models.JSONField(default=dict, verbose_name="配置信息")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "测试平台",
                "verbose_name_plural": "测试平台",
                "ordering": ["platform_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="BrowserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_data", models.JSONField(verbose_name="状态数据")),
                ("cookies", models.JSONField(default=list, verbose_name="Cookies")),
                (
                    "local_storage",
                    models.JSONField(default=dict, verbose_name="LocalStorage"),
                ),
                ("is_valid", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openai_api.testplatform",
                        verbose_name="测试平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "浏览器状态",
                "verbose_name_plural": "浏览器状态",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=100, unique=True, verbose_name="会话ID"),
                ),
                (
                    "test_type",
                    models.CharField(
                        default="standard", max_length=20, verbose_name="测试类型"
                    ),
                ),
                (
                    "prompt_file",
                    models.CharField(blank=True, max_length=200, verbose_name="提示词文件"),
                ),
                ("total_tests", models.IntegerField(default=0, verbose_name="总测试数")),
                (
                    "successful_tests",
                    models.IntegerField(default=0, verbose_name="成功数"),
                ),
                ("failed_tests", models.IntegerField(default=0, verbose_name="失败数")),
                (
                    "status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="状态"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openai_api.testplatform",
                        verbose_name="测试平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试会话",
                "verbose_name_plural": "测试会话",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkpoint_data", models.JSONField(verbose_name="检查点数据")),
                (
                    "last_test_index",
                    models.IntegerField(default=0, verbose_name="最后测试序号"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openai_api.testsession",
                        verbose_name="测试会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试检查点",
                "verbose_name_plural": "测试检查点",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_index", models.IntegerField(verbose_name="测试序号")),
                ("prompt", models.TextField(verbose_name="提示词")),
                ("response", models.TextField(blank=True, verbose_name="响应内容")),
                ("success", models.BooleanField(default=False, verbose_name="是否成功")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                ("duration", models.FloatField(default=0, verbose_name="耗时(秒)")),
                (
                    "simple_question",
                    models.CharField(blank=True, max_length=500, verbose_name="简单问题"),
                ),
                (
                    "simple_question_success",
                    models.BooleanField(default=False, verbose_name="简单问题成功"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="openai_api.testsession",
                        verbose_name="测试会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试结果",
                "verbose_name_plural": "测试结果",
                "ordering": ["session", "test_index"],
                "unique_together": {("session", "test_index")},
            },
        ),
    ]
