# Generated by Django 5.2 on 2026-02-23 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubjectiveTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                ("test_api_url", models.URLField(verbose_name="待测API地址")),
                (
                    "test_api_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="待测API Key",
                    ),
                ),
                (
                    "test_model_name",
                    models.CharField(max_length=100, verbose_name="待测模型名称"),
                ),
                (
                    "judge_model_name",
                    models.CharField(
                        default="内置超级裁判大模型",
                        max_length=100,
                        verbose_name="裁判模型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "准备就绪"),
                            ("running", "评测中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="测试题目(Prompt)")),
                (
                    "test_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="待测模型的回答"
                    ),
                ),
                (
                    "judge_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="裁判打分(比如1-10分)"
                    ),
                ),
                (
                    "judge_reasoning",
                    models.TextField(
                        blank=True, null=True, verbose_name="裁判点评/理由"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="subjective.subjectivetask",
                        verbose_name="所属任务",
                    ),
                ),
            ],
        ),
    ]
